services:
    sonarqube:
        image: sonarqube:lts
        container_name: sonarqube
        environment:
            - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
        ports:
            - "9000:9000"
        networks:
            - cicd-network
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
        ulimits:
            nofile:
                soft: 65536
                hard: 65536

    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        environment:
            - TZ=Asia/Jakarta
        privileged: true
        user: root
        ports:
            - "8080:8080"
            - "50000:50000"
        networks:
            - cicd-network
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/bin/docker
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock

networks:
    cicd-network:
        driver: bridge

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    jenkins_home:
